### ISSUE TITLE
possible case-sensitivity problems

### ISSUE THREAD

**Issue by bunnybones1** [goware/s3up#6]
<img width="148" alt="Screen Shot 2019-11-30 at 12 30 45 AM" src="https://user-images.githubusercontent.com/453513/69898038-aceb7680-1308-11ea-9acc-714286376d07.png">

It's possible hashes can be generated that are just case-different, like
zZyEhTGi
ZZyEhTGi

Should we be concerned?

**Comment by pkieltyka** [comment]
its a good question: cc: @dencoded @c2h5oh

**Comment by pkieltyka** [comment]
I think though the different cases are okay and will be supported by URLs, but lets confirm

**Comment by c2h5oh** [comment]
URLs are case-sensitive.
